# Permalinks
#
permalink:           pretty

# Setup
title:               Timothy Breckner Adams
tagline:             ''
description:         A place to host my thoughts, musings, ramblings, etc.
url:                 http://tbadams.com
baseurl:             ''
paginate:            5
plugins:             [jekyll-paginate, jekyll-seo-tag]

# About/contact
author:
  name:              Timothy Adams
  url:               http://tbadams.com
  email:             tbadams45@gmail.com

# Google services
google_analytics: UA-81234002-1
