# Permalinks
#
permalink:           pretty

# Setup
title:               Timothy Breckner Adams
tagline:             ''
description:         A place to host my thoughts, musings, ramblings, etc.
url:                 http://tbadams.com
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Timothy Adams
  url:               http://tbadams.com
  email:             tbadams45@gmail.com

# Custom vars
version:             1.0.0
