# Permalinks
#
permalink:           pretty

# Setup
title:               The Kingdom Breaks In
tagline:             ''
description:         Exploring the paradigm-breaking good news of Jesus.
url:                 http://kingdom-breaks-in.com
baseurl:             ''
paginate:            5
plugins:             [jekyll-paginate, jekyll-seo-tag]

# About/contact
author:
  name:              Timothy Adams
  url:               http://kingdom-breaks-in.com
  email:             tim@tbadams.com

# Google services
google_analytics: UA-81234002-1
